server:
  port: 8763
zuul:
  routes:
    CropDeal-Admin-Service:
      url: http://localhost:8701
    CropDeal-Dealer-Service:
      url: http://localhost:8702
    CropDeal-Farmer-Service:
      url: http://localhost:8703
    CropDeal-Payment-Service:
      url: http://localhost:8705
    

spring.application.name: CropDeal-Farmer-Service
spring.data.mongodb.uri: mongodb://navin:baba45@navintest-shard-00-00.f60cq.mongodb.net:27017,navintest-shard-00-01.f60cq.mongodb.net:27017,navintest-shard-00-02.f60cq.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-qlit1g-shard-0&authSource=admin&retryWrites=true&w=majority
spring.data.mongodb.database: crop_dealdb
 